require('dotenv').config();
const express=require('express'),cors=require('cors');
const auth=require('./middleware/authMiddleware'),rateLimit=require('./middleware/rateLimitMiddleware'),errors=require('./middleware/errorMiddleware');
const app=express();
app.disable('x-powered-by');
app.use(cors({origin:process.env.CORS_ORIGIN||true,credentials:false}));
app.use(express.json({limit:'64kb'}));
app.use(rateLimit);
app.get('/api/health',(req,res)=>res.json({ok:true,name:'Safe Space API',mode:'demo'}));
app.use('/api/auth',require('./routes/authRoutes'));
app.use(auth);
app.use('/api/mood',require('./routes/moodRoutes'));
app.use('/api/journal',require('./routes/journalRoutes'));
app.use('/api/counsellors',require('./routes/counsellorRoutes'));
app.use('/api/appointments',require('./routes/appointmentRoutes'));
app.use('/api/journey',require('./routes/journeyRoutes'));
app.use('/api/trends',require('./routes/trendRoutes'));
app.use('/api/support',require('./routes/supportRoutes'));
app.use('/api/admin',require('./routes/adminRoutes'));
app.get('/api/user/profile',(req,res)=>{
 const db=require('./config/database').load(),u=db.users.find(x=>x.id===req.user.id);
 if(!u)return res.sendStatus(404);
 res.json({id:u.id,name:u.name,email:u.email,language:u.language});
});
app.put('/api/user/profile',(req,res)=>res.json({ok:true,note:'Demo profile updates remain app-local in this build.'}));
app.use(errors);
const port=process.env.PORT||3000;
if(require.main===module)app.listen(port,()=>console.log('Safe Space API http://localhost:'+port));
module.exports=app;
